### ISSUE TITLE
Does not include .tsx deps when extension in import statement

### ISSUE THREAD

**Issue by amized** [antoine-coulon/skott#29] opened 2023-03-24 15:31 UTC
Thanks for the tool - I'm trying to run this over a react/typescript project with many .tsx dependencies.

Unfortuantely it seems the tool misses out when we import a tsx file without specifying the extension.

E.g. we have a file called SurveyVideo.tsx, and another file that imports it:
```
// Does not include SurveyVideo.tsx in the dep graph 
import * from "./SurveyVideo";
```

```
// Works
import * from "./SurveyVideo.tsx";
```

Can we get around this with the current config or is this a bug?

**Comment by antoine-coulon** [comment] 2023-03-24 22:03
Hello, thanks for reporting the issue @amized !

It's indeed not a bug nor a configurable thing, it's just a part of module resolution spec that was not implemented yet 🤦🏻‍♂️

TSX/JSX support from Skott is pretty new so there might be other issues, feel free to report them as well :) 

By the way, I'm already working on a quick implementation to resolve that issue. This will be included in a patch release tonight or tomorrow.

**Comment by antoine-coulon** [comment] 2023-03-24 22:29
@amized I just released a patch version 0.19.1 that should fix the module resolution problem. 

Could you please try with it and let me know if that fixes the issue? Thanks

**Comment by amized** [comment] 2023-03-29 14:03
hi @antoine-coulon I just tried again, now it's not picking up any imports:

```
$ skott --fileExtensions=.ts,.tsx src/pages/_app.tsx
```

![Screenshot 2023-03-29 at 10 02 52 AM](https://user-images.githubusercontent.com/13376866/228563266-54831150-9956-4fb9-975d-bc8d471245db.png)

**Comment by antoine-coulon** [comment] 2023-03-29 14:54
Hello @amized, could you please share a repro of your project or at least paste the content of your `src/pages/_app.tsx`? 
I can't reproduce that behavior on a project I got locally running with Next.js and TypeScript
Thanks!

**Comment by antoine-coulon** [comment] 2023-03-29 16:24
@amized 

It could also be to a `tsconfig` issue if you're ever using path aliases. Could you also paste it there to make the troubleshooting easier?

You might also want to try `skott --fileExtensions=.ts,.tsx src/pages/_app.tsx --trackThirdPartyDependencies` to check if some alias are considered third-party by Skott (which might be the case when path aliases could not be resolved correctly)

**Comment by antoine-coulon** [comment] 2023-04-11 07:25
Closing this as the problem should be outdated with latest releases. Feel free to re-open the issue if the problem persists

**Closed by antoine-coulon** 2023-04-11 07:25 UTC
